# Generated by Django 5.2.17 on 2026-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customization',
        ),
        migrations.AddField(
            model_name='product',
            name='customization_type',
            field=models.CharField(choices=[('full', 'Full Customization'), ('name_only', 'Name Only'), ('none', 'No Customization')], default='none', max_length=20),
        ),
    ]
